// This file is part of vscode-wagic.
//
// Copyright (C)2023 Vitty85 <https://github.com/Vitty85>
//
// Wagic Syntax is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either
// version 2 of the License, or (at your option) any later version.

/** Keywords (blue in the original plugin) */
export const keywords: string[] = [
    "any", "blink", "forsrc", "duplicateall", "halfall", "notrigger", "ability", "abilitycontroller", "add", "addtype", "novent", "delayed",
    "affinity", "after", "age", "all", "allsubtypes", "altercost", "alterdevoffset", "alterenergy", "alterexperience", "altermutationcounter",
    "alternativecostrule", "alterpoison", "altersurvoffset", "alteryidarocount", "and", "aslongas", "assorcery", "attackcost", "attackcostrule",
    "attackedalone", "attackpwcost", "attackrule", "backside", "becomes", "becomesmonarch", "becomesmonarchfoeof", "becomesmonarchof", "belong",
    "bestowrule", "blockcost", "blockcostrule", "blockrule", "bloodthirst", "boasted", "bonusrule", "bottomoflibrary", "bstw", "bury", "bushido",
    "buybackrule", "cantargetcard", "cantbeblockedby", "cantbeblockerof", "cantbetargetof", "canuntap", "card", "cards", "cascade", "castcard",
    "restricted", "casted", "cdaactive", "changecost", "checkex", "clone", "coinflipped", "coloringest", "combatphases", "combatends", "colors",
    "combatspiritlink", "combattriggerrule", "commandzonecast", "compare", "completedungeon", "conjure", "connect", "connectrule", "continue",
    "controller", "copied", "copiedacard", "copy", "costx", "count", "countb", "counter", "countermod", "counterremoved", "countershroud",
    "countersoneone", "countertrack", "coven", "create", "cumulativeupcost", "cycled", "damage", "deadcreart", "deadpermanent", "deathtouchrule",
    "delirium", "deplete", "destroy", "didattack", "didblock", "didnotcastnontoken", "didntattack", "discard", "discardbyopponent", "doboast",
    "doesntempty", "doforetell", "donothing", "dontremove", "dontshow", "dotrain", "doubleside", "draw", "dredgerule", "duplicate", "exilecast",
    "duplicatecounters", "dynamicability", "eachother", "epic", "equalto", "equalto~", "equip", "evicttypes", "evolve", "except", "exchangelife",
    "exert", "exileimp", "exploits", "explores", "fade", "fading", "fizzle", "fizzleto", "flanker", "flashbackrule", "flip", "flipped", "foelost",
    "fog", "forceclean", "forcedalive", "forcefield", "forcetype", "foreach", "forever", "freeze", "from", "fromplay", "frozen", "gravecast",
    "half", "hasdefender", "hasexerted", "haunt", "haunted", "head", "hiddenmoveto", "hmodifer", "identify", "imprint", "imprintedcard",
    "ingest", "itself", "kamiflip", "keepname", "kicked!", "kickerrule", "lastturn", "legendrule", "lessorequalcreatures", "lessorequallands",
    "lessthan", "lessthan~", "level", "librarybottom", "librarycast", "librarysecond", "librarytop", "life", "lifeleech", "lifelinkrule", "limit",
    "lifeloss", "lifeset", "livingweapon", "lord", "loseabilities", "loseability", "losesatype", "losesubtypesof", "lost", "madnessplayed", "max",
    "manafaceup", "manapool", "manifest", "maxcast", "maxlevel", "maxplay", "meld", "meldfrom", "message", "miracle", "modbenchant", "morbid",
    "morecardsthanopponent", "morethan", "morethan~", "morph", "morphrule", "most", "movedto", "moverandom", "moveto", "mutated", "mutateover",
    "mutateunder", "mutationover", "mutationunder", "myfoe", "myorigname", "myself", "myturnonly", "name", "named!", "nameingest", "never", "next",
    "newability", "newcolors", "newhook", "newtarget", "nextphase", "ninjutsu", "noevent", "nonbasicland", "nonstatic", "noreplace", "normal",
    "notatarget", "notblocked", "notdelirum", "notexerted", "notpaid", "notrg", "once", "oneonecounters", "oneshot", "only", "opponent", "out",
    "outnumbered", "opponentdamagedbycombat", "opponentpoisoned", "opponentpool", "opponentscontrol", "opponentturnonly", "options", "overloadrule",
    "ownerscontrol", "paid", "paidmana", "pay", "payzerorule", "persistrule", "phaseaction", "phaseactionmulti", "phasealter", "phasedin",
    "phaseout", "placefromthetop", "planeswalkerattack", "planeswalkerdamage", "planeswalkerrule", "plus", "poolsave", "positive", "proliferate",
    "powermorethancontrollerhand", "produceextra", "powermorethanopponenthand", "prevent", "preventallcombatdamage", "preventalldamage", "prowl",
    "propagate", "preventallnoncombatdamage", "previous", "producecolor", "provoke", "pumpboth", "pumppow", "pumptough", "putinplay", "raid",
    "putinplayrule", "rampage", "randomcard", "rebound", "reconfigure", "reduce", "reduceto", "regenerate", "rehook", "reject", "remake", "reveal",
    "removeallcounters", "removealltypes", "removecreaturesubtypes", "removedfromgame", "removefromcombat", "removemana", "removemc", "revealend",
    "removesinglecountertype", "removetypes", "repeat", "resetdamage", "restriction", "result", "retarget", "retracerule", "return", "revealtype",
    "revealuntil", "revealzone", "revolt", "sacrifice", "scry", "scryend", "scryzone", "selectmana", "serumpowder", "setblocker", "sethand",
    "setpower", "settoughness", "shackle", "shuffle", "sidecast", "single", "skill", "soulbondrule", "source", "sourceinplay", "sourcenottap",
    "sourcetap", "spellmover", "spent", "spiritlink", "srccontroller", "srcopponent", "standard", "steal", "surveil", "suspended", "suspendrule",
    "swap", "tail", "tails", "taketheinitiative", "tap", "target", "targetcontroller", "targetopponent", "teach", "terminate", "becomesringbearer",
    "text", "this", "thisforeach", "thisturn", "time", "toughnesslifegain", "to", "token", "tokencleanuprule", "tokencreated", "tosrc", "total",
    "trained", "trainer", "transforms", "trigger", "turn", "turnlimited", "turns", "tutorial", "type", "uent", "ueot", "undocpy", "unearthrule",
    "untap", "upcost", "upcostmulti", "uynt", "vampired", "vampirerule", "vanishing", "while", "winability", "wingame", "with", "withenchant",
    "won", "zerodead", "zone", "if", "then", "else", "activate", "unattach", "choice", "may", "beforenextturn", "~morethan~", "~lessthan~", "other",
    "~equalto~", "loseabilityend", "rolld", "end", "afterrevealed", "afterrevealedend", "variable", "winabilityend", "chooseanameopp", "chooseend",
    "chooseaname", "nonland", "upkeep", "optionone", "optiononeend", "optiontwo", "optiontwoend", "my", "ifnot", "blockers", "combatbegins",
    "multi", "powerstrike", "can", "play", "endofturn", "replacedraw", "cycle", "nextphasealter", "scrycore", "scrycoreend", "named", "beginofturn",
    "firstmain", "livingweapontoken", "flipacoin", "flipend", "chooseatype", "drawonly", "firstmainonly", "secondmain", "chooseacolor", "remove",
    "retargetfromplay", "attackersonly", "blockersonly", "combatdamageonly", "combatendsonly", "combatbeginsonly", "activatechooseacolor", "each",
    "activatechooseend", "powerpumpboth", "targetedpersonsbattlefield", "myattackersonly", "combat", "chargedraw", "manastrike", "activatedability",
    "manacostlifeloss", "combatbegin", "combatattackers", "combatblockers", "combatend", "grant", "grantend", "opponentupkeeponly", "myupkeeponly",
    "manacostlifestrike", "toughnesslifeloss", "main", "powerpumppow", "manacostlifelose", "opponentreplacedraw", "chosencolorend", "dredge",
    "activatechooseatype", "combatphaseswithmain", "agecountersoneone", "cantblocktarget", "endstep", "before", "attackers", "during", "noproftrg",
    "cleanup", "manacostlifegain", "opponentblockersonly", "powerlifegain", "cumulativeupcostmulti", "sourcenottapped", "oneonecountersstrike",
    "powercountersoneone", "powerlifeloss", "manacoststrike", "chargelifegain", "myupkeep", "untaponly", "toughnesstrike", "chargedeplete",
    "chargestrike", "manacostpumppow", "didcombatdamagetofoe", "manacostpumpboth", "manacostpumptough", "powerdraw", "colorspumpboth", "postbattle",
    "nonwall", "value", "twist", "emblem", "combatdamage", "convoke", "crew", "improvise", "delve", "emerge", "readytofight", "theringtempts",
    "oppoattacked", "untp", "nocost", "removeallsubtypes", "removeallcolors",
];

/** Zones (purple in the original plugin) */
export const zones: string[] = [
    "mycastingzone", "myrestrictedcastingzone", "mycommandplay", "myhandlibrary", "mygravelibrary", "opponentgravelibrary", "mygraveexile",
    "opponentgraveexile", "opponentcastingzone", "opponentrestrictedcastingzone", "opponentcommandplay", "opponenthandlibrary", "mynonplaynonexile",
    "opponentnonplaynonexile", "myhandexilegrave", "opponenthandexilegrave", "myzones", "opponentzones", "mysideboard", "mycommandzone", "myreveal",
    "mygraveyard", "mybattlefield", "myhand", "mylibrary", "mystack", "myexile", "opponentsideboard", "opponentcommandzone", "opponentreveal",
    "opponentgraveyard", "opponentbattlefield", "opponenthand", "opponentlibrary", "opponentstack", "opponentexile", "ownersideboard", "ownerreveal",
    "ownercommandzone", "ownergraveyard", "ownerbattlefield", "ownerinplay", "ownerhand", "ownerlibrary", "ownerstack", "ownerexile", "sideboard",
    "commandzone", "reveal", "graveyard", "battlefield", "inplay", "hand", "library", "nonbattlezone", "stack", "exile", "previousbattlefield",
    "targetedpersonssideboard", "targetedpersonsreveal", "targetedpersonscommandzone", "targetedpersonsgraveyard", "targetedpersonsbattlefield",
    "targetedpersonsinplay", "targetedpersonshand", "targetedpersonslibrary", "targetedpersonsstack", "targetedpersonsexile", "targetcontrollerexile",
    "targetcontrollersideboard", "targetcontrollerreveal", "targetcontrollercommandzone", "targetcontrollergraveyard", "targetcontrollerbattlefield",
    "targetcontrollerinplay", "targetcontrollerhand", "targetcontrollerlibrary", "targetcontrollerstack", "targetedplayersideboard",
    "targetedplayerhand", "targetedplayercommandzone", "targetedplayergraveyard", "targetedplayerbattlefield", "targetedplayerinplay",
    "targetedplayerlibrary", "targetedplayerexile", "targetedplayerstack", "targetedplayerreveal",
];

/** Triggers (dark-red in the original plugin) */
export const triggers: string[] = [
    "@tappedformana", "@becomesmonarchof", "@drawof", "@combat", "@boasted", "@targeted", "@lifelostfoeof", "@noncombatdamagefoeof",
    "@takeninitiativeof", "@takeninitiativefoeof", "@energizedof", "@counteradded", "@totalcounteradded", "@totalcounterremoved",
    "@dierolled", "@damageof", "@sacrificed", "@combatdamaged", "@shuffledfoeof", "@cycled", "@poisonedfoeof", "@foretold", "@energizedfoeof",
    "@discarded", "@tokencreated", "@phasedin", "@untapped", "@drawfoeof", "@combatdamagefoeof", "@exploited", "@poisonedof", "@exerted",
    "@movedTo", "@experiencedof", "@counterremoved", "@vampired", "@countermod", "@experiencedfoeof", "@shuffledof", "@lifeof", "@noncombatdamaged",
    "@trained", "@defeated", "@dungeoncompleted", "@surveiled", "@damagefoeof", "@combatdamageof", "@coinflipped", "@noncombatdamageof", "@movedto",
    "@damaged", "@explored", "@lifefoeof", "@lifelostof", "@transformed", "@facedup", "@lord", "@drawn", "@castcard", "@tapped", "@mutated",
    "@each endofturn", "@each beginofturn", "@each upkeep", "@each firstmain", "@each combatbegins", "@each attackers", "@each blockers",
    "@each combatdamage", "@each combatends", "@each secondmain", "@each end", "@each cleanup", "@each untap", "@each my endofturn",
    "@each my beginofturn", "@each my upkeep", "@each my firstmain", "@each my combatbegins", "@each my attackers", "@each my blockers",
    "@each my combatdamage", "@each my combatends", "@each my secondmain", "@each my end", "@each my cleanup", "@each my untap", "@each draw",
    "@each opponent endofturn", "@each opponent beginofturn", "@each opponent upkeep", "@each opponent firstmain", "@each opponent combatbegins",
    "@each opponent attackers", "@each opponent blockers", "@each opponent combatdamage", "@each opponent combatends", "@each opponent secondmain",
    "@each opponent end", "@each opponent cleanup", "@each opponent untap", "@next endofturn", "@next beginofturn", "@next upkeep", "@each my draw",
    "@next firstmain", "@next combatbegins", "@next attackers", "@next blockers", "@next combatdamage", "@next combatends", "@next secondmain",
    "@each opponent draw", "@next end", "@next cleanup", "@next untap", "@proliferateof", "@proliferatefoeof", "@ninjutsued", "@ringtemptedof",
    "@ringtemptedfoeof", "@becomesmonarchfoeof", "@bearerchosen", "@bearernewchosen", "@each targetedplayer endofturn", "@each targetedplayer end",
    "@each targetedplayer beginofturn", "@each targetedplayer upkeep", "@each targetedplayer firstmain", "@each targetedplayer combatbegins",
    "@each targetedplayer attackers", "@each targetedplayer blockers", "@each targetedplayer combatdamage", "@each targetedplayer combatends",
    "@each targetedplayer secondmain", "@each targetedplayer cleanup", "@each targetedplayer untap", "@scryed", "@producedmana",
];

/** Macros (orange in the original plugin) */
export const macros: string[] = [
    "__CYCLING__", "__BASIC_LANDCYCLING__", "_DIES_", "_TRAINING_", "_PARTNER_", "_GOAD_", "_REBOUND_", "_POPULATE_", "_FEROCIOUS_", "_ATTACKING_",
    "_BLOCKED_", "_HEROIC_", "_RALLY_", "_LANDFALL_", "_ADDENDUM_", "_CONSTELLATION_", "_SCRY_", "_SCRY1_", "_SCRY2_", "_SCRY3_", "_ZOMBIETOKEN_",
    "_SCRY4_", "_SCRY5_", "_FABRICATE_", "_ENRAGE_", "_SECOND_DRAW_", "_ADAPT_", "_BATTALION_", "_CHAMPION_", "_METALCRAFT_", "_KNIGHTTOKEN_",
    "_THRESHOLD_", "_SPLICEARCANE_", "_RIPPLE_", "_RECOVER_", "_CLASH_", "_PROLIFERATE_", "_SCAVENGE_", "_MONSTROSITY_", "_OUTLAST_", "_ECHO_",
    "_INVESTIGATE_", "_ASCEND_", "_CITY'S_BLESSING_", "_EXPLORE_", "_MONARCH_CONTROLLER_", "_MONARCH_OPPONENT_", "_INITIATIVE_CONTROLLER_",
    "_INITIATIVE_OPPONENT_", "_TREASURE_", "_CASTHISTORIC_", "_MENTOR_", "_SURVEIL1_", "_SURVEIL2_", "_SURVEIL3_", "_UNDERGROWTH_", "_RIOT_",
    "_AFTERLIFETOKEN_", "_LEARN_", "_SPECTACLE_", "_ADVENTURE_", "_EXTORT_", "_FORETELL_", "_LOOT_", "_UNEARTH_", "__PLAY_TOP_FROM_EXILE__",
    "_WARD_", "_RENOWN_", "_BLINK_UEOT_", "_CONNIVES_", "_ETERNALIZE_", "_DISCARD&DRAW_", "_PUNCH_", "_MUST_BE_BLOCKD_", "_ANGELTOKEN_",
    "_BEASTTOKEN_", "_DRAGONTOKEN_", "_ELEPHANTTOKEN_", "_GOBLINTOKEN_", "_INSECTTOKEN_", "_PHYREXIANMITETOKEN_", "_REDELEMENTALTOKEN_",
    "_HARNESSED_LIGHTNING_", "_SAPROLINGTOKEN_", "_SERVOTOKEN_", "_SOLDIERTOKEN_", "_SPIRITTOKEN_", "_THOPTERTOKEN_", "_WOLFTOKEN_",
    "_HARNESSED_CONTROL_", "_AMASSORC1_", "_AMASSORC2_", "_AMASSORC3_", "_AMASSORC4_", "_AMASSORC5_", "_AMASSZOMBIE1_", "_AMASSZOMBIE2_",
    "_AMASSZOMBIE3_", "_AMASSZOMBIE4_", "_AMASSZOMBIE5_", "_RINGTEMPTS_", "_AMASSSLIVER1_", "_AMASSSLIVER2_", "_AMASSSLIVER3_",
    "_AMASSSLIVER4_", "_AMASSSLIVER5_",
];

/** Constants (gray in the original plugin) */
export const constants: string[] = [
    "abundantlife", "allbattlefieldcardtypes", "allgravecardtypes", "allmyname", "auras", "azorius", "boros", "bothalldead", "bushidopoints",
    "calculateparty", "canforetellcast", "cantargetcre", "cantargetmycre", "cantargetoppocre", "castx", "chosencolor", "chosenname", "chosentype",
    "commonblack", "commonblue", "commongreen", "commonred", "commonwhite", "controllerturn", "converge", "convertedcost:", "countallspell",
    "countedamount", "countedbamount", "countmycrespell", "countmynoncrespell", "crewtotalpower", "currentphase", "currentturn", "evictth",
    "cursedscrollresult", "dimir", "direction", "dualfaced", "epicactivated", "evictb", "evictg", "evictmc", "evictpw", "evictr", "evictu",
    "evictw", "excessdamage", "findfirsttype", "findlasttype", "fivetimes", "fourtimes", "fullpaid", "gear", "genrand", "golgari", "gruul",
    "halfdown", "halfpaid", "halfup", "handsize", "hasability", "hascnt", "hasevict", "hasmansym", "hasprey", "hasstorecard", "highest",
    "highestlifetotal", "iscopied", "isflipped", "ishuman", "izzet", "kicked", "lastdiefaces", "lastflipchoice", "lastflipresult", "lastrollchoice",
    "lastrollresult", "lifegain", "lifelost", "lifetotal", "lowestlifetotal", "magusofscrollresult", "math", "mathend", "minus", "minusend",
    "mutations", "mybattlefieldcardtypes", "myblackpoolcount", "mybluepoolcount", "mycolnum", "mycolorlesspoolcount", "mygravecardtypes",
    "mygreenpoolcount", "myname", "mypoisoncount", "mypoolcount", "mypos", "myredpoolcount", "mysnowblackpoolcount", "mysnowbluepoolcount",
    "mysnowcolorlesspoolcount", "mysnowgreenpoolcount", "mysnowpoolcount", "mysnowredpoolcount", "mysnowwhitepoolcount", "mytarg", "odomain",
    "mywhitepoolcount", "numofcommandcast", "numoftypes", "oalldead", "oattackedcount", "ocoven", "ocycledcount", "odcount", "odevotionoffset",
    "odiffinitlife", "odnoncount", "odrewcount", "odungeoncompleted", "oenergy", "oexperience", "ohalfinitlife", "ohandcount", "oinitiative",
    "oinstsorcount", "olandb", "olandc", "olandg", "olandr", "olandu", "olandw", "olastshlturn", "olibrarycount", "omonarch", "onumcreswp",
    "onumofcommandcast", "onumofidentitycols", "oplifegain", "oplifelost", "oppbattlefieldcardtypes", "oppgravecardtypes", "oppofindfirsttype",
    "oppofindlasttype", "opponentblackpoolcount", "opponentbluepoolcount", "opponentcolorlesspoolcount", "opponentgreenpoolcount", "opponentturn",
    "opponentlifetotal", "opponentpoisoncount", "opponentpoolcount", "opponentredpoolcount", "opponentsnowblackpoolcount", "oppototalmana",
    "opponentsnowbluepoolcount", "opponentsnowcolorlesspoolcount", "opponentsnowgreenpoolcount", "opponentsnowpoolcount", "otherpower", "orzhov",
    "opponentsnowredpoolcount", "opponentsnowwhitepoolcount", "opponentwhitepoolcount", "oppototalcololorsinplay", "oppsametypecreatures",
    "pdnoncount", "ostartinglife", "ostormcount", "osurveiloffset", "otherconvertedcost", "othertoughness", "othertype", "oyidarocount", "prex",
    "palldead", "pdomain", "pancientooze", "pattackedcount", "pbasiclandtypes", "pcoven", "pcycledcount", "pdauntless", "pdcount", "pinitiative",
    "pdevotionoffset", "pdiffinitlife", "pdrewcount", "pdungeoncompleted", "penergy", "permanent", "pexperience", "pgbzombie", "pginstantsorcery",
    "pgmanainstantsorcery", "phalfinitlife", "phandcount", "pinstsorcount", "plandb", "plandc", "plandg", "plandr", "plandu", "plandw", "prodmana",
    "plastshlturn", "plibrarycount", "plusend", "pmonarch", "pnumcreswp", "pnumofcommandcast", "pnumofidentitycols", "power", "powertotalinplay",
    "pstormcount", "psurveiloffset", "pwr", "pwrtotalinplay", "pwrtotatt", "pwrtotblo", "pyidarocount", "rakdos", "revealedmana", "revealedp",
    "revealedt", "sametypecreatures", "scryedcards", "selesnya", "simic", "snowdiffmana", "srclastdiefaces", "srclastrollchoice", "thirdup", "ths:",
    "thrice", "srclastrollresult", "startinglife", "startingplayer", "stored", "targetedcurses", "thatmuch", "thirddown", "thirdpaid", "waste",
    "thstotalinplay", "thstotatt", "thstotblo", "totalcololorsinplay", "totaldmg", "totalmana", "totcnt", "totcntall", "totcntart", "totcntbat",
    "totcntcre", "totcntenc", "totcntlan", "totcntpla", "totmanaspent", "toughness", "toughnesstotalinplay", "twice", "urzatron", "usedmana",
    "withpartner", "worshipped", "colorless", "green", "blue", "red", "black", "white", "alternative", "buyback", "flashback", "kicker", "facedown",
    "faceup", "bestow", "anyamount", "attacking", "backname", "blockable", "blocked", "blocking", "cantarget ", "cardid", "children", "cmana",
    "color ", "controllerdamager", "damaged", "damager", "description", "discarded", "dredgeable", "enchanted", "equals", "equipped", "evictname",
    "exerted", "expansion", "extracostshadow", "foretold", "geared", "hasbackside", "hasconvoke", "hasflashback", "haskicker", "haspartner", "hasx",
    "icon", "lastnamechosen", "leveler", "manab", "manacost", "manag", "manar", "manau", "manaw", "mtgid", "multicolor", "mychild", "mycurses",
    "myeqp", "mysource", "mytgt", "mytotem", "notshare!", "numofcols", "opponentdamager", "pairable", "parents", "partname", "preyname",
    "rarity", "recent", "sourcecard", "tapped", "targetedplayer", "targetter", "title", "unknown", "upto", "zpos", "notany", "oppohasdead",
    "modified", "battleready", "findfirsttypenonland", "share", "types", "findfirsttypecreature", "controllerlife", "convertedcost", "untapped",
    "bothalldeadcreature", "findfirsttypeartifact", "findfirsttypepermanent", "oppofindfirsttypecreature", "oppofindfirsttypenonpermanent",
    "findfirsttypenonpermanent", "findfirsttypeelemental", "findfirsttypeelf", "findfirsttypeland", "oppofindfirsttypeland", "opponentpoolsave",
    "findfirsttypeplaneswalker", "findfirsttypeenchantment", "hasmansymw", "hasmansymr", "hasmansymg", "hasmansymu", "hasmansymb", "mypoolsave",
    "prexx", "opponentdamagecount", "thatmuchcountersoneone", "plifelost", "poisoncount", "oppofindfirsttypenonland", "lowest", "usedmanab",
    "usedmanag", "usedmanaw", "usedmanau", "usedmanar", "usedmanatot", "toxicity", "hastoxic", "ninelands", "mytgtforced", "numofactivation",
    "pringtemptations", "oringtemptations", "myhasdead", "oppotgt", "ctrltgt", "ohandsize", "isattacker", "couldattack",
];

/** Basic abilities (gray in the original plugin) */
export const basicabilities: string[] = [
    "trample", "forestwalk", "islandwalk", "mountainwalk", "swampwalk", "plainswalk", "flying", "first", "double", "strike", "fear", "flash",
    "haste", "lifelink", "reach", "shroud", "vigilance", "defender", "banding", "protection", "protection from green", "protection from blue",
    "protection from red", "protection from black", "protection from white", "unblockable", "wither", "persist", "retrace", "exalted", "weak",
    "nofizzle", "shadow", "reachshadow", "foresthome", "islandhome", "mountainhome", "swamphome", "plainshome", "cloud", "cantattack", "split",
    "mustattack", "cantblock", "doesnotuntap", "opponentshroud", "indestructible", "intimidate", "deathtouch", "horsemanship", "cantregen",
    "oneblocker", "infect", "poisontoxic", "poisontwotoxic", "poisonthreetoxic", "phantom", "wilting", "vigor", "changeling", "absorb", "treason",
    "unearth", "cantlose", "cantlifelose", "cantmilllose", "snowlandwalk", "nonbasiclandwalk", "strong", "storm", "phasing", "second", "flanking",
    "affinityartifacts", "affinityplains", "affinityforests", "affinityislands", "affinitymountains", "affinityswamps", "exiledeath", "sunburst",
    "affinitygreencreatures", "cantwin", "nomaxhand", "leyline", "playershroud", "controllershroud", "legendarylandwalk", "desertlandwalk",
    "snowforestlandwalk", "snowplainslandwalk", "snowmountainlandwalk", "snowislandlandwalk", "snowswamplandwalk", "canattack", "hydra", "undying",
    "poisonshroud", "noactivatedability", "notapability", "nomanaability", "onlymanaability", "poisondamager", "soulbond", "lure", "nolegend",
    "canplayfromgraveyard", "tokenizer", "mygraveexiler", "oppgraveexiler", "librarydeath", "shufflelibrarydeath", "offering", "evadebigger",
    "spellmastery", "nolifegain", "nolifegainopponent", "auraward", "madness", "protectionfromcoloredspells", "mygcreatureexiler", "devoid",
    "oppgcreatureexiler", "zerocast", "trinisphere", "canplayfromexile", "libraryeater", "cantchangelife", "combattoughness", "cantpaylife",
    "cantbesacrified", "skulk", "menace", "nosolo", "mustblock", "dethrone", "overload", "shackler", "flyersonly", "tempflashback", "renown",
    "legendruleremove", "canttransform", "asflash", "conduited", "canblocktapped", "oppnomaxhand", "cantcrew", "hiddenface", "anytypeofmana",
    "necroed", "cantpwattack", "canplayfromlibrarytop", "canplaylandlibrarytop", "canplaycreaturelibrarytop", "canplayartifactlibrarytop",
    "canplayinstantsorcerylibrarytop", "showfromtoplibrary", "showopponenttoplibrary", "totemarmor", "discardtoplaybyopponent", "modular",
    "adventure", "mentor", "prowess", "nofizzle alternative", "hasotherkicker", "partner", "canbecommander", "iscommander", "threeblockers",
    "handdeath", "inplaydeath", "inplaytapdeath", "gainedexiledeath", "gainedhanddeath", "cycling", "foretell", "anytypeofmanaability", "boast",
    "twoboast", "replacescry", "hasnokicker", "undamageable", "lifefaker", "doublefacedeath", "gaineddoublefacedeath", "twodngtrg", "nodngopp",
    "nodngplr", "canplayauraequiplibrarytop", "counterdeath", "dungeoncompleted", "perpetuallifelink", "perpetualdeathtouch", "noncombatvigor",
    "nomovetrigger", "wascommander", "showopponenthand", "showcontrollerhand", "hasreplicate", "isprey", "hasdisturb", "daybound", "nightbound",
    "decayed", "hasstrive", "isconspiracy", "hasaftermath", "noentertrg", "nodietrg", "training", "energyshroud", "expshroud", "countershroud",
    "nonight", "nodamageremoved", "backgroundpartner", "bottomlibrarydeath", "noloyaltydamage", "nodefensedamage", "affinityallcreatures",
    "affinitycontrollercreatures", "affinityopponentcreatures", "affinityalldeadcreatures", "affinityparty", "affinityenchantments", "mutate",
    "affinitybasiclandtypes", "affinitytwobasiclandtypes", "affinitygravecreatures", "affinityattackingcreatures", "affinitygraveinstsorc",
    "canloyaltytwice", "attached", "fresh", "snowplainswalk", "snowislandwalk", "snowswampwalk", "snowmountainwalk", "snowforestwalk", "desertwalk",
    "poisonfourtoxic", "poisonfivetoxic", "poisonsixtoxic", "poisonseventoxic", "poisoneighttoxic", "poisonninetoxic", "poisontentoxic", "ringbearer",
    "eqpasinst", "canloyaltyasinst",
];

/** Card types (black/default in the original plugin) */
export const types: string[] = [
    "abian", "abyss", "advisor", "aetherborn", "ajani", "alara", "ally", "aminatou", "amonkhet", "angel", "angrath", "antausia", "antelope",
    "ape", "arcane", "arcavios", "archer", "archon", "arkhos", "arlinn", "art", "artifact", "artificer", "ashiok", "assassin", "assembly", "atog",
    "aura", "aurochs", "autobot", "avatar", "azgol", "azra", "background", "baddest", "badger", "bahamut", "barbarian", "bard", "basic", "basilisk",
    "basri", "bat", "battle", "bear", "beast", "beaver", "beeble", "beholder", "belenon", "berserker", "biggest", "bird", "blood", "boar", "bolas",
    "brainiac", "bringer", "brushwagg", "bureaucrat", "calix", "camel", "capenna", "carrier", "cartouche", "cat", "centaur", "cephalid", "chandra",
    "chameleon", "chicken", "child", "chimera", "citizen", "clamfolk", "class", "cleric", "clue", "cockatrice", "conspiracy", "construct", "cow",
    "contraption", "coward", "crab", "creature", "cridhe", "crocodile", "curse", "cyborg", "cyclops", "dack", "dakkon", "daretti", "dauthi", "deer",
    "davriel", "demigod", "demon", "desert", "designer", "devil", "dihada", "dinosaur", "djinn", "dog", "dominaria", "domri", "donkey", "dovin",
    "dragon", "drake", "dreadnought", "drone", "druid", "dryad", "duck", "dungeon", "dwarf", "eaturecray", "echoir", "efreet", "egg", "elder",
    "eldraine", "eldrazi", "elemental", "elephant", "elf", "elk", "ellywick", "elminster", "elspeth", "elves", "enchant", "enchantment", "equilor",
    "equipment", "ergamon", "estrid", "etiquette", "eye", "fabacin", "faerie", "ferret", "fiora", "fish", "flagbearer", "food", "forest", "fox",
    "fractal", "freyalise", "frog", "fungus", "gamer", "gargantikar", "gargoyle", "garruk", "gate", "giant", "gideon", "gith", "gnoll", "gnome",
    "goat", "gobakhan", "goblin", "god", "golem", "gorgon", "grandchild", "gremlin", "griffin", "grist", "gus", "hag", "halfling", "harpy",
    "hatificer", "head", "hellion", "hero", "hippo", "hippogriff", "homarid", "homunculus", "horror", "horse", "host", "huatli", "human", "hydra",
    "hyena", "igpay", "ikoria", "illusion", "imp", "incarnation", "incubator", "insect", "instant", "interrupt", "inzerva", "iquatana", "ir",
    "island", "ixalan", "jace", "jackal", "jared", "jaya", "jellyfish", "jeska", "juggernaut", "kaladesh", "kaldheim", "kamigawa", "kangaroo",
    "karn", "karsus", "kasmina", "kavu", "kaya", "kephalai", "killbot", "kinshala", "kiora", "kirin", "kithkin", "knight", "kobold", "kolbahan",
    "kor", "koth", "kraken", "krav", "kylem", "kyneth", "lady", "lair", "lamia", "lammasu", "land", "lathiel", "leech", "legend", "legendary",
    "lesson", "leviathan", "lhurgoyf", "licid", "liliana", "lizard", "locus", "lolth", "lord", "lorwyn", "lukka", "luvion", "manticore", "master",
    "masticore", "meditation", "mercadia", "mercenary", "merfolk", "metathran", "mime", "mine", "minion", "minotaur", "minsc", "mirrodin", "moag",
    "mole", "monger", "mongoose", "mongseng", "monk", "monkey", "moonfolk", "mordenkainen", "mountain", "mouse", "mummy", "muraganda", "mutant",
    "myr", "mystic", "naga", "nahiri", "narset", "nastiest", "nautilus", "nephilim", "new", "nightmare", "nightstalker", "niko", "ninja", "nissa",
    "nixilis", "noble", "noggle", "nomad", "nymph", "octopus", "ogre", "oko", "ongoing", "ooze", "orc", "orgg", "otter", "ouphe", "ox", "oyster",
    "pangolin", "paratrooper", "peasant", "pegasus", "penguin", "pest", "phelddagrif", "phenomenon", "phoenix", "phyrexia", "phyrexian", "pilot",
    "pirate", "plains", "plane", "planeswalker", "plant", "player", "powerstone", "praetor", "processor", "proper", "pyrulea", "rabbit", "rabiah",
    "raccoon", "ral", "ranger", "rat", "rath", "ravnica", "realm", "rebel", "reflection", "regatha", "rhino", "rigger", "rogue", "rowan", "rune",
    "sable", "saga", "saheeli", "salamander", "samurai", "samut", "saproling", "sarkhan", "satyr", "scarecrow", "scheme", "scientist", "scorpion",
    "scout", "segovia", "serpent", "serra", "shade", "shaman", "shandalar", "shapeshifter", "shark", "sheep", "shenmeng", "ship", "shrine", "siege",
    "siren", "skeleton", "slith", "sliver", "slug", "snake", "snow", "soldier", "soltari", "sorcery", "sorin", "spawn", "specter", "spellshaper",
    "sphere", "sphinx", "spider", "spike", "spirit", "sponge", "spy", "squid", "squirrel", "starfish", "summon", "surrakar", "survivor", "swamp",
    "szat", "tamiyo", "tarkir", "tasha", "teferi", "tentacle", "tetravite", "teyo", "tezzeret", "thalakos", "theros", "thopter", "thrull", "tibalt",
    "tiefling", "token", "tower", "townsfolk", "trap", "treasure", "treefolk", "tribal", "trilobite", "triskelavite", "troll", "turtle", "tyvar",
    "ugin", "ulgrotha", "unicorn", "urza", "valla", "vanguard", "vampire", "vampyre", "vedalken", "vehicle", "venser", "viashino", "villain",
    "vivien", "volver", "vraska", "vryn", "waiter", "wall", "walrus", "warlock", "warrior", "weird", "werewolf", "whale", "wildfire", "will", "cur",
    "windgrace", "wizard", "wolf", "wolverine", "wombat", "worker", "world", "worm", "wraith", "wrenn", "wrestler", "wurm", "xenagos", "xerex",
    "yanggu", "yanling", "yeti", "zariel", "zendikar", "zhalfir", "zombie", "zubera", "tobecast", "sur", "tomb", "of", "annihilation", "agadeem",
    "the", "undercrypt", "tobereturn", "marauder", "airlift", "chaplain", "valiant", "protector", "akoum", "teeth", "watchdog", "alpine", "igneous",
    "whispering", "raven", "ancestral", "anger", "day", "night", "amplifire", "destiny", "marauders", "anthem", "treasureartifacttoken", "inkling",
    "disenchant", "terror", "braingeyser", "shivan", "regrowth", "lotus", "br", "monstrous", "Arni", "Brokenbrow", "bloodletting", "phandelver",
    "affected", "gathering", "goliath", "crossbreed", " labs", "watermark", "ru", "genesis", "mage", "brambleweft", "behemoth", "gladewalker",
    "ritualist", "jiang", "m", "control", "two", "or", "more", "vampires", "gr", "rb", "peer", "through", "depths", "mists", "kgoblin", "kfox",
    "kmoonfolk", "krat", "ksnake", "a", "spell", "aether", "burst", "kjeldoran", "war", "cry", "one", "kind", "saclands", "less", "creatures", "rg",
    "artifacts", "enchantments", "lands", "t", "r", "b", "u", "d", "s", "w", "g", "l", "x", "e", "c", "p", "gw", "rw", "wu", "gu", "bg", "wb",
    "h", "i", "ub", "q", "ur", "xx", "n", "color", "kindle", "scion", "skyshipped", "splinter", "stangg", "twin", "sunweb", "visitation", "vecna",
    "mirror", "mad", "phantasm", "cost", "word", "autostack", "anycnt", "anytarget", "propagation", "proliferation",
];

/** All word lists merged for completion purposes */
export const allWords: string[] = [
    ...new Set([
        ...zones,
        ...constants,
        ...basicabilities,
        ...keywords,
        ...types,
        ...triggers,
        ...macros,
    ]),
];

/**
 * Lines that should receive syntax analysis (prefixes that start a relevant line).
 * All entries MUST be lowercase because callers always compare against `.toLowerCase()` output.
 * The TextMate grammar uses the uppercase literal `#AUTO_DEFINE` directly in its regex;
 * the grammar is case-sensitive while the runtime code does a case-insensitive comparison.
 */
export const RELEVANT_LINE_PREFIXES: string[] = [
    "text=",
    "name=",
    "power=",
    "toughness=",
    "type=",
    "subtype=",
    "grade=",
    "backside=",
    "partner=",
    "#auto_define",
];

/** Patterns inside which words should NOT be flagged as unknown (e.g. name(...) blocks) */
export const SKIP_REGIONS: Array<{ open: string; close: string }> = [
    { open: "name(", close: ")" },
    { open: "named!:", close: ":!" },
];
